function [fitresult, gof] = createFit(h)
%CREATEFIT(H)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: h
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Jan-2014 16:43:48


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], h );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( ft );
opts.SmoothingParam = 0.999999317310205;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h1 = plot( fitresult, xData, yData );
legend( h1, 'h', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
ylabel( 'h' );
grid on


